# Generated by Django 5.2.7 on 2025-10-12 08:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер'), ('leader', 'Руководитель направления'), ('moderator', 'Модератор'), ('president', 'Президент Ассоциации'), ('worker', 'Работник (Админ)'), ('head_admin', 'Руководитель отдела')], default='volunteer', max_length=20, verbose_name='Роль в системе')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Профиль одобрен')),
                ('pending_changes', models.JSONField(blank=True, null=True, verbose_name='Ожидающие изменения')),
                ('is_active_volunteer_title', models.BooleanField(default=False, verbose_name="Имеет звание 'Активный волонтер'")),
                ('photo', models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/', verbose_name='Фотография')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Группа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone_privacy', models.CharField(choices=[('private', 'Только модераторам'), ('volunteers', 'Только волонтерам'), ('public', 'Всем')], default='private', max_length=15)),
                ('telegram_privacy', models.CharField(choices=[('private', 'Только модераторам'), ('volunteers', 'Только волонтерам'), ('public', 'Всем')], default='private', max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
