# Generated by Django 5.2.7 on 2025-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_moderation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название направления')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название школы')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='directions',
            field=models.ManyToManyField(blank=True, to='users.direction', verbose_name='Участвует в направлениях'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_leader',
            field=models.ManyToManyField(blank=True, to='users.school', verbose_name='Руководит школами'),
        ),
    ]
