# Generated by Django 5.2.7 on 2025-10-12 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_direction_school_user_directions_user_school_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_direction', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
