# Generated by Django 5.2.7 on 2025-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_direction_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_leader',
        ),
        migrations.AddField(
            model_name='user',
            name='school_leader_of',
            field=models.ManyToManyField(blank=True, related_name='leaders', to='users.school', verbose_name='Руководит школами'),
        ),
    ]
