# Generated by Django 5.2.7 on 2025-10-12 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_school_leader_user_school_leader_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания периода')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание (необязательно)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Период активности',
                'verbose_name_plural': 'Периоды активности',
                'ordering': ['start_date'],
            },
        ),
    ]
