# Generated by Django 5.2.7 on 2025-11-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moderation_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pending_changes',
        ),
    ]
