# Generated by Django 5.2.7 on 2025-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_moderation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True, verbose_name='Ожидающие изменения'),
        ),
    ]
