# Generated by Django 5.2.7 on 2025-11-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_moderation_comment_user_pending_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moderation_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pending_changes',
        ),
    ]
