# Generated by Django 5.2.7 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_auditlog_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность (для сотрудников)'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кабинет/Местоположение'),
        ),
    ]
