# Generated by Django 5.2.7 on 2025-11-20 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_job_title_user_office_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (офис)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Главное описание (вверху)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram (ссылка или ник)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='Текст миссии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Наша Миссия', max_length=100, verbose_name='Заголовок миссии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_1_num',
            field=models.CharField(default='500+', max_length=20, verbose_name='Цифра 1 (напр. 500+)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_1_text',
            field=models.CharField(default='Волонтеров', max_length=100, verbose_name='Подпись 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_2_num',
            field=models.CharField(default='50+', max_length=20, verbose_name='Цифра 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_2_text',
            field=models.CharField(default='Мероприятий', max_length=100, verbose_name='Подпись 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_3_num',
            field=models.CharField(default='5', max_length=20, verbose_name='Цифра 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_3_text',
            field=models.CharField(default='Лет работы', max_length=100, verbose_name='Подпись 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram канал'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='О нас', max_length=255, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь (если применимо)'),
        ),
    ]
