# Generated by Django 5.2.7 on 2025-11-22 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_aboutpage_content_aboutpage_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='leader',
        ),
        migrations.AddField(
            model_name='direction',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='directions_led', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
