# Generated by Django 5.2.7 on 2025-12-07 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_aboutphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperiod',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='about_me_privacy',
            field=models.CharField(choices=[('private', '🔒 Только я и Админы'), ('volunteers', '👥 Все волонтеры'), ('public', '🌐 Все (Публично)')], default='volunteers', max_length=15, verbose_name='Кто видит Био?'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_privacy',
            field=models.CharField(choices=[('private', '🔒 Только я и Админы'), ('volunteers', '👥 Все волонтеры'), ('public', '🌐 Все (Публично)')], default='volunteers', max_length=15, verbose_name='Кто видит Instagram?'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_privacy',
            field=models.CharField(choices=[('private', '🔒 Только я и Админы'), ('volunteers', '👥 Все волонтеры'), ('public', '🌐 Все (Публично)')], default='volunteers', max_length=15, verbose_name='Кто видит LinkedIn?'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Наша Миссия', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_1_num',
            field=models.CharField(default='500+', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_1_text',
            field=models.CharField(default='Волонтеров', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_2_num',
            field=models.CharField(default='50+', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_2_text',
            field=models.CharField(default='Мероприятий', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_3_num',
            field=models.CharField(default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat_3_text',
            field=models.CharField(default='Лет работы', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='О нас', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='О себе (Bio)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_privacy',
            field=models.CharField(choices=[('private', '🔒 Только я и Админы'), ('volunteers', '👥 Все волонтеры'), ('public', '🌐 Все (Публично)')], default='volunteers', max_length=15, verbose_name='Кто видит телефон?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_privacy',
            field=models.CharField(choices=[('private', '🔒 Только я и Админы'), ('volunteers', '👥 Все волонтеры'), ('public', '🌐 Все (Публично)')], default='volunteers', max_length=15, verbose_name='Кто видит Telegram?'),
        ),
        migrations.DeleteModel(
            name='AboutPhoto',
        ),
    ]
