# Generated by Django 5.2.7 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_activityperiod_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания периода'),
        ),
    ]
