# Generated by Django 5.2.7 on 2026-03-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_activityperiod_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('email', 'Email'), ('phone', 'Телефон'), ('site', 'Сайт'), ('address', 'Адрес'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Платформа')),
                ('label', models.CharField(max_length=120, verbose_name='Текст (что показываем)')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка/контакт (URL, @username, номер)')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='Иконка (опционально, FontAwesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='users.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: Контакт',
                'verbose_name_plural': 'О нас: Контакты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutExtraBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('icon', models.CharField(blank=True, default='fa-solid fa-lightbulb', max_length=60, verbose_name='Иконка FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_blocks', to='users.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: Доп.блок',
                'verbose_name_plural': 'О нас: Доп.блоки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Число (например 135+)')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('icon', models.CharField(blank=True, default='fa-solid fa-chart-line', max_length=60, verbose_name='Иконка FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_items', to='users.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: Статистика',
                'verbose_name_plural': 'О нас: Статистика',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=220, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='fa-solid fa-star', max_length=60, verbose_name='Иконка FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_blocks', to='users.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: Ценность/блок',
                'verbose_name_plural': 'О нас: Ценности/блоки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
