# Generated by Django 5.2.7 on 2026-03-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_aboutcontactlink_aboutextrablock_aboutstatitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontactlink',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='aboutextrablock',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='aboutstatitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='aboutvalueblock',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='aboutextrablock',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='aboutstatitem',
            name='icon',
        ),
        migrations.AddField(
            model_name='aboutextrablock',
            name='button_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='aboutextrablock',
            name='button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome class, e.g. 'fab fa-telegram'", max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='label',
            field=models.CharField(blank=True, help_text='Текст кнопки/подпись', max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('email', 'Email'), ('phone', 'Phone'), ('site', 'Website'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutcontactlink',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutextrablock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutextrablock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutextrablock',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutextrablock',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='aboutstatitem',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.aboutpage'),
        ),
        migrations.AlterField(
            model_name='aboutstatitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutstatitem',
            name='label',
            field=models.CharField(help_text='Например: Волонтёров', max_length=80, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='aboutstatitem',
            name='number',
            field=models.CharField(help_text='Например: 135+', max_length=24, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='aboutstatitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutvalueblock',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon name, e.g. 'fa-users'", max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutvalueblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutvalueblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutvalueblock',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutvalueblock',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
