# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_aboutcontactlink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutextrablock',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutstatitem',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutvalueblock',
            name='about',
        ),
        migrations.AddField(
            model_name='user',
            name='candidate_approved',
            field=models.BooleanField(default=False, help_text='Одобрен как кандидат (может заходить на сайт, но пока без волонтёрских прав).', verbose_name='Кандидат одобрен (договор подписан)'),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_access',
            field=models.BooleanField(default=False, help_text='Полный доступ волонтёра (открывается автоматически на 3-й отметке или вручную).', verbose_name='Доступ волонтёра открыт (3 визита)'),
        ),
        migrations.CreateModel(
            name='VolunteerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата визита')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_visits', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AboutContactLink',
        ),
        migrations.DeleteModel(
            name='AboutExtraBlock',
        ),
        migrations.DeleteModel(
            name='AboutStatItem',
        ),
        migrations.DeleteModel(
            name='AboutValueBlock',
        ),
        migrations.AddConstraint(
            model_name='volunteervisit',
            constraint=models.UniqueConstraint(fields=('user', 'visit_date'), name='unique_user_visit_per_day'),
        ),
    ]
