# Generated by Django 5.2.7 on 2026-03-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_aboutextrablock_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='candidate_approved',
            field=models.BooleanField(default=False, help_text='Одобрен как кандидат: может заходить на сайт, но без волонтёрских прав.', verbose_name='Кандидат одобрен (договор подписан)'),
        ),
        migrations.CreateModel(
            name='AboutContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-link', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_volunteer_access', models.BooleanField(default=False, verbose_name='Только для волонтёров')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='users.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutExtraBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-lightbulb', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_blocks', to='users.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-chart-line', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_items', to='users.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutValueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-star', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_blocks', to='users.aboutpage')),
            ],
        ),
    ]
