# Generated by Django 5.2.7 on 2026-03-08 22:24

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def normalize_candidate_states(apps, schema_editor):
    User = apps.get_model('users', 'User')
    VolunteerVisit = apps.get_model('users', 'VolunteerVisit')

    # 1) Удаляем дубли визитов за один и тот же день, оставляем самый ранний id.
    seen = set()
    for visit in VolunteerVisit.objects.all().order_by('user_id', 'visit_date', 'id'):
        key = (visit.user_id, visit.visit_date)
        if key in seen:
            visit.delete()
            continue
        seen.add(key)

    now = timezone.now()

    # 2) Приводим статусы пользователей к одной логике.
    for user in User.objects.all():
        visits = list(VolunteerVisit.objects.filter(user_id=user.id).order_by('visit_date', 'created_at', 'id'))
        visit_count = len(visits)
        latest_visit = visits[-1] if visits else None

        # Если уже есть полный доступ, вычищаем кандидата из подвешенного состояния.
        if user.is_approved:
            user.volunteer_access = True
            if user.volunteer_access_granted_at is None:
                if latest_visit and visit_count >= 3:
                    user.volunteer_access_granted_at = latest_visit.created_at
                    user.volunteer_access_granted_by_id = latest_visit.marked_by_id
                    if not user.is_old_volunteer:
                        user.new_volunteer_until = latest_visit.created_at + timedelta(days=14)
                else:
                    user.volunteer_access_granted_at = now
                    # Такие записи считаем старыми волонтёрами, пришедшими на сайт позже.
                    user.is_old_volunteer = True
                    user.new_volunteer_until = None
            elif not user.is_old_volunteer and user.new_volunteer_until is None:
                user.new_volunteer_until = user.volunteer_access_granted_at + timedelta(days=14)

            if user.is_old_volunteer:
                user.new_volunteer_until = None

            user.save(update_fields=[
                'volunteer_access',
                'volunteer_access_granted_at',
                'volunteer_access_granted_by',
                'is_old_volunteer',
                'new_volunteer_until',
            ])
            continue

        # Если визитов 3+, а доступа нет — автоматически выдаём полный доступ.
        if visit_count >= 3:
            granted_at = latest_visit.created_at if latest_visit else now
            user.candidate_approved = True
            user.volunteer_access = True
            user.is_approved = True
            user.is_old_volunteer = False
            user.volunteer_access_granted_at = granted_at
            user.volunteer_access_granted_by_id = latest_visit.marked_by_id if latest_visit else None
            user.new_volunteer_until = granted_at + timedelta(days=14)
            user.save(update_fields=[
                'candidate_approved',
                'volunteer_access',
                'is_approved',
                'is_old_volunteer',
                'volunteer_access_granted_at',
                'volunteer_access_granted_by',
                'new_volunteer_until',
            ])
            continue

        # Если есть визиты, но кандидатский статус не включён — включаем.
        if visit_count > 0 and not user.candidate_approved:
            user.candidate_approved = True
            user.save(update_fields=['candidate_approved'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_candidate_approved_aboutcontactlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_old_volunteer',
            field=models.BooleanField(default=False, help_text='Используется при ручной выдаче доступа тем, кто давно волонтёр, но только сейчас зарегистрировался на сайте.', verbose_name='Старый волонтёр'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_volunteer_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="До какого времени показывать статус 'Новый волонтёр'"),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_access_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда выдан полный доступ'),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_access_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_volunteer_access_to', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал полный доступ'),
        ),
        migrations.AddField(
            model_name='volunteervisit',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.RunPython(normalize_candidate_states, migrations.RunPython.noop),
    ]
