# Generated by Django 5.2.7 on 2026-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_candidate_approved_aboutcontactlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontactlink',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='aboutcontactlink',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('email', 'Email'), ('phone', 'Телефон'), ('site', 'Сайт'), ('address', 'Адрес'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
