# Generated by Django 5.2.7 on 2026-03-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_aboutcontactlink_options_and_more'),
        ('users', '0026_user_is_old_volunteer_user_new_volunteer_until_and_more'),
    ]

    operations = [
    ]
