# Generated by Django 5.2.7 on 2026-03-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_is_old_volunteer_and_contact_platform'),
        ('users', '0027_merge_20260309_0416'),
    ]

    operations = [
    ]
