# Generated by Django 5.2.7 on 2026-03-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_volunteervisit_comment_compat'),
        ('users', '0028_merge_20260309_1810'),
    ]

    operations = [
    ]
