# Generated by Django 5.2.7 on 2026-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20260310_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, upload_to='homepage/', verbose_name='Фотография в верхнем блоке')),
                ('quote_text', models.TextField(blank=True, verbose_name='Цитата')),
                ('quote_author', models.CharField(blank=True, max_length=160, verbose_name='Автор цитаты')),
                ('quote_role', models.CharField(blank=True, max_length=160, verbose_name='Подпись автора')),
                ('quote_photo', models.ImageField(blank=True, upload_to='homepage/', verbose_name='Фотография автора')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
