# Generated by Django 5.2.7 on 2026-09-10 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_previous_homepage(apps, schema_editor):
    Page=apps.get_model('users','HomePage')
    Slide=apps.get_model('users','HomeSlide')
    Quote=apps.get_model('users','HomeQuote')
    alias=schema_editor.connection.alias
    for page in Page.objects.using(alias).all():
        if page.hero_image:
            Slide.objects.using(alias).create(page_id=page.pk,image=page.hero_image.name)
        if page.quote_text and page.quote_author:
            Quote.objects.using(alias).create(page_id=page.pk,text=page.quote_text,author_name=page.quote_author,author_role=page.quote_role,photo=page.quote_photo.name)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quotes_per_view',
            field=models.PositiveSmallIntegerField(choices=[(1, 'По одной'), (2, 'По две'), (3, 'По три')], default=1, verbose_name='Показ цитат'),
        ),
        migrations.CreateModel(
            name='HomeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('author_name', models.CharField(blank=True, max_length=160, verbose_name='Имя автора')),
                ('author_role', models.CharField(blank=True, max_length=160, verbose_name='Подпись автора')),
                ('photo', models.ImageField(blank=True, upload_to='homepage/quotes/', verbose_name='Фотография автора')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на источник')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Участник сайта')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/slides/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание фотографии')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='users.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(preserve_previous_homepage, migrations.RunPython.noop),
    ]
