# Generated by Django 5.2.7 on 2026-09-10 17:02

from django.db import migrations, models


def move_legacy_contacts(apps,schema_editor):
    Page=apps.get_model('users','AboutPage');Link=apps.get_model('users','AboutContactLink')
    alias=schema_editor.connection.alias
    for page in Page.objects.using(alias).all():
        for platform in ['instagram','telegram']:
            raw=getattr(page,platform,'')
            if raw and not Link.objects.using(alias).filter(about_id=page.pk,platform=platform).exists():
                Link.objects.using(alias).create(about_id=page.pk,platform=platform,label=platform.title(),url=raw,requires_volunteer_access=platform=='telegram')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_home_slides_and_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstatitem',
            name='source',
            field=models.CharField(choices=[('manual', 'Ввести вручную'), ('volunteers', 'Волонтёры'), ('active', 'Активные волонтёры'), ('workers', 'Работники'), ('leaders', 'Руководители направлений'), ('school_leaders', 'Руководители школ'), ('schools', 'Школы'), ('directions', 'Направления'), ('events', 'Мероприятия')], default='manual', max_length=24, verbose_name='Откуда брать число'),
        ),
        migrations.RunPython(move_legacy_contacts,migrations.RunPython.noop),
    ]
