# Generated by Django 5.2.7 on 2026-09-10 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_normalize_eventhero_constraint'),
        ('users', '0032_about_stat_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Вид помощи')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы')),
                ('active', models.BooleanField(default=True, verbose_name='Доступен для начислений')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_awards', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_awards', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.contributionkind')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='users.contributionaward')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('date', models.DateField(verbose_name='Дата выполненной работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='contributionaward',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='users.contributionwork'),
        ),
        migrations.AddConstraint(
            model_name='contributionaward',
            constraint=models.UniqueConstraint(fields=('work', 'member', 'kind'), name='unique_work_member_kind'),
        ),
    ]
