# Generated by Django 5.2.7 on 2026-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_contributionkind_contributionaward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionwork',
            name='submission',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
