# Generated by Django 5.2.7 on 2026-09-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_normalize_eventhero_constraint'),
        ('users', '0035_remove_legacy_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionwork',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_works', to='users.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='contributionwork',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_works', to='users.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='direction',
            name='cover',
            field=models.ImageField(blank=True, upload_to='directions/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, verbose_name='О направлении'),
        ),
        migrations.AddField(
            model_name='direction',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='aya_directions', to='events.event'),
        ),
        migrations.AddField(
            model_name='direction',
            name='featured_members',
            field=models.ManyToManyField(blank=True, related_name='featured_in_directions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direction',
            name='featured_only',
            field=models.BooleanField(default=False, verbose_name='Показывать активную команду'),
        ),
        migrations.AddField(
            model_name='direction',
            name='intro',
            field=models.CharField(blank=True, max_length=240, verbose_name='Коротко о направлении'),
        ),
        migrations.AddField(
            model_name='school',
            name='cover',
            field=models.ImageField(blank=True, upload_to='schools/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, verbose_name='О школе'),
        ),
        migrations.AddField(
            model_name='school',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='users.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='school',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='aya_schools', to='events.event'),
        ),
        migrations.AddField(
            model_name='school',
            name='intro',
            field=models.CharField(blank=True, max_length=240, verbose_name='Коротко о школе'),
        ),
        migrations.AddField(
            model_name='school',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='aya_schools', to=settings.AUTH_USER_MODEL, verbose_name='Участники школы'),
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Предмет / специализация')),
                ('bio', models.TextField(blank=True, verbose_name='О преподавателе')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Фотография')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Профиль на сайте')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='users.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240, verbose_name='Тема занятия')),
                ('starts_at', models.DateTimeField(verbose_name='Начало занятия')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание занятия')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='Место / кабинет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Занятие отменено')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.school')),
                ('teachers', models.ManyToManyField(blank=True, related_name='lessons', to='users.schoolteacher', verbose_name='Преподаватели')),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
    ]
