# Generated by Django 5.2.7 on 2026-09-12 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_contributionwork_direction_contributionwork_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Занятия проводятся'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('moderator', 'Модератор'), ('president', 'Президент Ассоциации'), ('worker', 'Работник (Админ)'), ('head_admin', 'Начальник отдела')], default='volunteer', max_length=20, verbose_name='Роль в системе'),
        ),
        migrations.CreateModel(
            name='PointProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='За какую помощь')),
                ('date', models.DateField(verbose_name='Дата помощи')),
                ('description', models.TextField(blank=True, verbose_name='Описание помощи')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_proposals', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.direction')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school')),
                ('volunteers', models.ManyToManyField(related_name='proposed_awards', to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.contributionwork')),
            ],
        ),
    ]
