# Generated by Django 5.2.7 on 2026-09-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_cancellation_reason_event_cancelled_and_more'),
        ('users', '0038_student_leadership_and_school_members'),
    ]

    operations = [
        migrations.AlterField(model_name="pointproposal", name="work", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.contributionwork")),
        migrations.AddField(
            model_name='pointproposal',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
