# Generated by Django 5.2.7 on 2026-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_import_legacy_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Бохтар', 'Бохтар'), ('Бустон', 'Бустон'), ('Вахдат', 'Вахдат'), ('Гиссар', 'Гиссар'), ('Гулистон', 'Гулистон'), ('Душанбе', 'Душанбе'), ('Истаравшан', 'Истаравшан'), ('Истиклол', 'Истиклол'), ('Исфара', 'Исфара'), ('Канибадам', 'Канибадам'), ('Куляб', 'Куляб'), ('Левакант', 'Левакант'), ('Нурек', 'Нурек'), ('Пенджикент', 'Пенджикент'), ('Рогун', 'Рогун'), ('Турсунзаде', 'Турсунзаде'), ('Худжанд', 'Худжанд'), ('Хорог', 'Хорог')], max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Лечебный', 'Лечебный'), ('Стоматологический', 'Стоматологический'), ('Педиатрический', 'Педиатрический'), ('Фармацевтический', 'Фармацевтический'), ('Медико-профилактический', 'Медико-профилактический')], max_length=200, verbose_name='Факультет'),
        ),
    ]
