# Generated by Django 5.2.7 on 2026-09-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_fixed_profile_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('deferred', 'Отложено'), ('completed', 'Завершено')], default='not_started', max_length=16)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_tour_topic')],
            },
        ),
    ]
