# Generated by Django 5.2.7 on 2026-09-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_cancellation_reason_event_cancelled_and_more'),
        ('users', '0043_tour_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='featured_members',
            field=models.ManyToManyField(blank=True, related_name='featured_in_schools', to=settings.AUTH_USER_MODEL, verbose_name='Активная команда'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('intro', models.CharField(blank=True, max_length=240, verbose_name='Коротко о клубе')),
                ('description', models.TextField(blank=True, verbose_name='О клубе')),
                ('cover', models.ImageField(blank=True, upload_to='clubs/', verbose_name='Обложка')),
                ('active', models.BooleanField(default=True, verbose_name='Встречи проводятся')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='users.direction', verbose_name='Направление')),
                ('events', models.ManyToManyField(blank=True, related_name='aya_clubs', to='events.event', verbose_name='Мероприятия')),
                ('featured_members', models.ManyToManyField(blank=True, related_name='featured_in_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Активная команда')),
                ('leaders', models.ManyToManyField(blank=True, related_name='clubs_led', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные')),
                ('members', models.ManyToManyField(blank=True, related_name='aya_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='users.school', verbose_name='Школа')),
            ],
        ),
        migrations.AddField(
            model_name='contributionwork',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_works', to='users.club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='users.club'),
        ),
        migrations.AddField(
            model_name='pointproposal',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club', verbose_name='Клуб'),
        ),
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240, verbose_name='Тема встречи')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='Место')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Встреча отменена')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='users.club')),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('worker', 'Работник'), ('head_admin', 'Начальник отдела')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
