# Generated by Django 5.2.7 on 2026-09-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_clubs_and_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointproposal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
