# Generated by Django 5.2.7 on 2026-09-28 00:31

import users.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_notification_event_key_birthdaygreeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='video_file',
            field=models.FileField(blank=True, upload_to=users.media_uploads.video_upload_path, validators=[users.media_uploads.validate_video], verbose_name='Видеофайл'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_poster',
            field=models.ImageField(blank=True, upload_to='video_posters/', verbose_name='Обложка видео'),
        ),
    ]
