# Generated by Django 5.2.7 on 2026-09-28 12:31

from django.db import migrations, models


"""Stable subject keys for presentation-only journal grouping."""
import re

def subject_key(section, object_id, before, after, actor_id=None):
    data={**(before or {}),**(after or {})}
    parents={'events.EventPhoto':('event','events.Event'),'events.EventVideo':('event','events.Event'),'events.EventAttendance':('event','events.Event'),'events.EventHero':('event','events.Event'),'users.SchoolTeacher':('school','users.School'),'users.SchoolLesson':('school','users.School'),'users.ClubMeeting':('club','users.Club'),'users.ContributionAward':('work','users.ContributionWork'),'users.PermissionOverride':('user','users.User'),'users.ActivityPeriod':('user','users.User')}
    if section in parents:
        field,model=parents[section];value=data.get(field) or data.get(field+'_id')
        if str(value).isdigit():return model+':'+str(value)
    if section in {'users.User','users.Direction','users.School','users.Club','users.ContributionWork','events.Event'} and str(object_id).isdigit():return section+':'+str(object_id)
    if section in {'public_profile','open_profile_photo','reveal_phone','reveal_birthday','open_contact'} and str(object_id).isdigit():return 'users.User:'+str(object_id)
    path=data.get('path','')
    for pattern,model in [(r'^/(?:profile|people)/(\d+)(?:/|$)','users.User'),(r'^/events/(\d+)(?:/|$)','events.Event'),(r'^/schools/(\d+)(?:/|$)','users.School'),(r'^/directions/(\d+)(?:/|$)','users.Direction'),(r'^/clubs/(\d+)(?:/|$)','users.Club'),(r'^/points/works/(\d+)(?:/|$)','users.ContributionWork')]:
        match=re.match(pattern,path)
        if match:return model+':'+match.group(1)
    if section in {'my_profile','profile_edit'} and actor_id:return 'users.User:'+str(actor_id)
    if section:return 'section:'+section+(':'+str(object_id) if object_id else '')
    return ''


def backfill(apps,schema_editor):
    Entry=apps.get_model('users','JournalEntry');batch=[]
    for row in Entry.objects.using(schema_editor.connection.alias).all().iterator(chunk_size=500):
        row.subject_key=subject_key(row.section,row.object_id,row.before,row.after,row.actor_id)
        # Old anonymous visits cannot reliably be attributed to the same guest.
        row.actor_key='user:'+str(row.actor_id) if row.actor_id else 'legacy:'+str(row.pk)
        batch.append(row)
        if len(batch)==500:Entry.objects.using(schema_editor.connection.alias).bulk_update(batch,['subject_key','actor_key']);batch=[]
    if batch:Entry.objects.using(schema_editor.connection.alias).bulk_update(batch,['subject_key','actor_key'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_aboutpage_video_file_aboutpage_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='actor_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='subject_key',
            field=models.CharField(blank=True, db_index=True, max_length=240),
        ),
        migrations.RunPython(backfill,migrations.RunPython.noop),
    ]
