# Generated by Django 5.2.7 on 2026-09-28 17:17

import users.logo_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_journalentry_actor_key_journalentry_subject_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG, JPEG или WebP, до 8 МБ. Логотип показывается целиком, без обрезки.', upload_to='clubs/logos/', validators=[users.logo_validation.validate_logo], verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='direction',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG, JPEG или WebP, до 8 МБ. Логотип показывается целиком, без обрезки.', upload_to='directions/logos/', validators=[users.logo_validation.validate_logo], verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG, JPEG или WebP, до 8 МБ. Логотип показывается целиком, без обрезки.', upload_to='schools/logos/', validators=[users.logo_validation.validate_logo], verbose_name='Логотип'),
        ),
    ]
