# Generated by Django 5.2.7 on 2025-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено модератором')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. участников')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
