# Generated by Django 5.2.7 on 2025-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_event_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='report_text',
            field=models.TextField(blank=True, verbose_name='Текст отчета'),
        ),
        migrations.AlterField(
            model_name='eventhero',
            name='role_name',
            field=models.CharField(max_length=100, verbose_name='Роль'),
        ),
    ]
