# Generated by Django 5.2.7 on 2025-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_is_approved_alter_event_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public_for_guests',
            field=models.BooleanField(default=False, verbose_name='Видно для гостей (без регистрации)'),
        ),
    ]
