# Generated by Django 5.2.7 on 2026-03-08 18:38

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_event_heroes(apps, schema_editor):
    EventHero = apps.get_model('events', 'EventHero')
    duplicates = (
        EventHero.objects.values('event_id', 'user_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for row in duplicates:
        heroes = list(
            EventHero.objects.filter(event_id=row['event_id'], user_id=row['user_id']).order_by('id')
        )
        for hero in heroes[1:]:
            hero.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhero',
            options={'ordering': ['user__last_name', 'user__first_name', 'id']},
        ),
        migrations.RunPython(dedupe_event_heroes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventhero',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_hero_per_user'),
        ),
    ]
