# Generated by Django 5.2.7 on 2026-03-08 22:25

from django.conf import settings
from django.db import migrations, models


def cleanup_eventhero_duplicates(apps, schema_editor):
    EventHero = apps.get_model('events', 'EventHero')
    seen = set()
    for hero in EventHero.objects.all().order_by('event_id', 'user_id', 'id'):
        key = (hero.event_id, hero.user_id)
        if key in seen:
            hero.delete()
            continue
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cleanup_eventhero_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventhero',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_hero_per_user'),
        ),
    ]
