# Generated by Django 5.2.7 on 2026-03-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventhero_options_and_more'),
        ('events', '0007_eventhero_unique_event_hero_per_user'),
    ]

    operations = [
    ]
