# Generated by Django 5.2.7 on 2026-03-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_cleanup_participants_and_eventhero_unique'),
        ('events', '0008_merge_20260309_0416'),
    ]

    operations = [
    ]
