# Generated by Django 5.2.7 on 2026-09-12 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_normalize_eventhero_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько людей нужно'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='events.event')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_event_attendance')],
            },
        ),
    ]
