# Generated by Django 5.2.7 on 2026-09-28 00:31

import users.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_preserve_deleted_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideo',
            name='poster',
            field=models.ImageField(blank=True, upload_to='video_posters/', verbose_name='Обложка видео'),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='title',
            field=models.CharField(blank=True, max_length=180, verbose_name='Название видео'),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='video_file',
            field=models.FileField(blank=True, upload_to=users.media_uploads.video_upload_path, validators=[users.media_uploads.validate_video], verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
